add sequential naming tools
xamarin/binding-tools-for-swift pull request #838
Opened 2024-03-26 14:26 UTC by stephen-hawley

Added sequential naming

2024-03-27 19:44 UTC, dalexsoto approved these changes

2024-03-28 12:19 UTC, mandel-macaque requested changes

2024-03-28 15:04 UTC, mandel-macaque commented on SwiftReflector/Naming/SequentialNamer.cs
> +		object nameLock = new object ();
```suggestion
		int current;
		string prefix;
```

2024-03-28 15:05 UTC, mandel-macaque commented on SwiftReflector/Naming/SequentialNamer.cs
> +			}
```suggestion
			return CSSafeNaming.SafeIdentifier ($"{prefix}{name}{Interlocked.Increment(ref current)}");
```

2024-04-05 14:57 UTC, rolfbjarne approved these changes

2024-04-11 14:08 UTC, mcumming approved these changes

2024-04-11 14:08 UTC, rolfbjarne approved these changes

2024-04-11 14:10 UTC, merged